-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "Customer_registrationDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Devolution" ALTER COLUMN "Dev_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Purchase" ALTER COLUMN "Purchase_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "Sale_date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "Supplier_registrationDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "User_registrationDate" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Warranty" ALTER COLUMN "Warranty_date" SET DEFAULT CURRENT_TIMESTAMP;
